In [2]:
import numpy as np

In [5]:
a=np.array([1,2,3])

In [7]:
a

array([1, 2, 3])

In [9]:
type(a)

numpy.ndarray

In [10]:
import sys

In [11]:
sys.getsizeof(a)

124

In [12]:
a=np.array([1,2,3,4],dtype=np.int8)

In [13]:
sys.getsizeof(a)

116

In [17]:
my2Darray=[[1,2,3],[1,2,3]]

In [15]:
my2Darray


array([1, 2, 3, 4, 5, 6])

In [18]:
b2D=np.array(my2Darray)

In [19]:
b2D

array([[1, 2, 3],
       [1, 2, 3]])

In [20]:
b2D=np.array([[1,2,1],[1,2,1]])

In [21]:
b2D


array([[1, 2, 1],
       [1, 2, 1]])

In [23]:
b2D.dtype

dtype('int32')

In [24]:
b2D.shape


(2, 3)

In [25]:
b2D.size

6

In [26]:
b2D.ndim

2

In [29]:
np.empty((1,2))

array([[-4.84804527e-302, -1.28951308e+244]])