In [1]:
import numpy as np

In [2]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
list(range(2,5))

[2, 3, 4]

In [4]:
list(range(2,10,2))

[2, 4, 6, 8]

In [5]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

## np.arange  a=array range is same as python range()

In [6]:
np.arange(100,200,2)

array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124,
       126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150,
       152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176,
       178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198])

In [7]:
np.arange(100,200).sum()

14950

## .sum() to find sum of all values, .mean() to find mean, np.median(value) to find median

In [8]:
a=np.arange(100,200,2)

In [9]:
a.sum()

7450

In [10]:
np.sum(a)

7450

In [11]:
a.mean()

149.0

In [12]:
np.median(a)

149.0

## np.std(value) For Standard Deviation

In [13]:
np.std(a)

28.861739379323623

## to find variance np.var(a)

In [14]:
np.var(a)

833.0

In [15]:
a=np.array([[1,2,3],[2,4,5]])

In [16]:
b=a[0]

In [17]:
b[0]

1

In [18]:
a[0][0]

1

In [20]:
a[1][2]

5

In [21]:
a[1,2]

5

In [25]:
arr=np.arange(100).reshape((10,10))

In [23]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [27]:
arr[1:3,2:5]

array([[12, 13, 14],
       [22, 23, 24]])

In [30]:
arr[8,2:5]

array([82, 83, 84])

In [32]:
arr[::2,::2]

array([[ 0,  2,  4,  6,  8],
       [20, 22, 24, 26, 28],
       [40, 42, 44, 46, 48],
       [60, 62, 64, 66, 68],
       [80, 82, 84, 86, 88]])

In [36]:
arr[1::2,0::2]

array([[10, 12, 14, 16, 18],
       [30, 32, 34, 36, 38],
       [50, 52, 54, 56, 58],
       [70, 72, 74, 76, 78],
       [90, 92, 94, 96, 98]])

## for minimum and maximum value value.min() and value.max()


In [37]:
arr.min()

0

In [38]:
arr.max()

99