## Slection Notes

In [1]:
import numpy as np
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

## arange means array range

In [2]:
a[[True,True,False,True,True]]

array([0, 1, 3, 4])

In [4]:
b=np.arange(25)

In [5]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [9]:
a**2

array([ 0,  1,  4,  9, 16])

In [11]:
a<5


array([ True,  True,  True,  True,  True])

In [12]:
a%2==0

array([ True, False,  True, False,  True])

In [13]:
a[a%2==0]

array([0, 2, 4])

In [15]:
b[b%5==0]

array([ 5, 10, 15, 20, 25])

In [16]:
(b%2==0)&(b%5==0)

array([False, False, False, False, False, False, False, False,  True,
       False, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False])

In [17]:
b[(b%2==0)&(b%5==0)]

array([10, 20])

In [18]:
arr=np.arange(2,50)

In [20]:
arr[(arr>5)&(arr<40)&(arr%2==0)]

array([ 6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [23]:
arr[(arr<20)|(arr%2==0)]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48])

In [30]:
arr2=arr
arr=np.arange(22)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21])

## To copy and create different array from array that doesnt change on changing parent array use .copy()

In [32]:
arr3=arr.copy()
arr=np.arange(100)
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21])

In [38]:
a="Hacke Aadarsh Saurav Chahat"
a.split(" ")

['Hacke', 'Aadarsh', 'Saurav', 'Chahat']

In [44]:
a=np.arange(50)


In [51]:
arr4=np.reshape(a,(10,5))


In [52]:
arr4


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [53]:
arr4[0,0]=100

In [54]:
arr4


array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49]])

In [55]:
np.ravel(arr4)

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49])

In [57]:
dc=np.arange(25)

In [58]:
cd=np.reshape(dc,(5,5))

In [59]:
cd

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [60]:
np.ravel(cd)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])